services:
  web:
    build: .
    container_name: django_web
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - backend

  mongo:
    image: mongo:7
    container_name: mongo_db
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - mongo_data:/data/db
    env_file:
      - .env
    networks:
      - backend

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express_ui
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
